[workspace]

members = [
	"net-timescale-api",
	"net-agent-api",
]

[workspace.dependencies]
net-proto-api = { version = "=0.1.1-bbafe57", registry = "net-registry" }

log = "0.4.17"
log4rs = "1.2.0"
